### ISSUE TITLE
Always prompts for serial number

### ISSUE THREAD

**Issue by Sithuk** [stars-4x/starswine#1]
The game always prompts for the serial number on startup. Is starswine able to save the serial after it is entered the first time so there is no further prompt?

**Comment by raptor** [comment]
Yes. It should save it with creating an INI file within the emulated environment. This is at `otvdm\WINDOWS\Stars.ini`.

Make sure the zip file is extracted and you have permissions to the folder.

**Comment by Sithuk** [comment]
Thank you for the quick response. I am running from an unzipped folder. I can see there is a Stars.ini file at the following location.

"..\otvdm\WINDOWS\Stars.ini"

I seem to have full access rights to the Stars.ini file. I right mouse click on the file and select properties. On the security tab there are ticks for my user in all the items in the ALLOW column, except for "special permissions".

Could it be an issue with how I am running the stars.bat file? Does it have to be run as admin? I have the same permissions for the stars.bat file as I do for the Stars.ini file.

What field in the Stars.ini file is used to store the serial?

**Comment by raptor** [comment]
The serial is encoded in the INI file so there's not a good way to enter it in manually. If the INI exists in the proper folder then that means it should be getting saved.

Regular usage is to just run the `stars.bat` file.

When I speak of permissions, I mean the top level starswine folder and all sub-folders should have you as owner.

You could try to run the `stars.bat` as admin. This is the first I've heard of it not working. What OS are you on?

**Comment by Sithuk** [comment]
I'm the owner for the starswine4 folder. 

OS is Windows 10 version 21H2 (Build 19044.1415). I don't have admin rights.

**Comment by raptor** [comment]
I just tested `starswine4.zip`, freshly extracted, into a different folder with a non-admin user on Windows 10 and I could not duplicate your issue. My license worked and was saved just fine upon next restart.

You could try the windows7 version to see if it works any better, or delete everything and try again.

Also there is a discord where others could help, too:   https://discord.gg/Ctdx7h6UZS

**Comment by Sithuk** [comment]
I just tried again on a separate windows 10 pc and got the same result of the serial not being saved. The OS version on the second machine is 21H1 (Build 19043.1526).

Running as admin resulted in an error: "Windows cannot find '.\otvdm\otvdm.exe'. Make sure you typed the name correctly, and then try again.

I tried running the windows 7 alternative version and got the same issue (although I had to set stars.exe to run in windows 7 compatibility mode otherwise I got a crash on exit).

What version of OS are you using on your development system?

**Comment by raptor** [comment]
I have access to many Windows 10 boxes ranging from versions ~14000 to mid ~18000 (right now this one is 18363.418). I'll need to find one with the newest update like yours.

It still sounds like an extraction issue, which would give that exact error running as 'admin' (although admin should not be needed). What did you use to extract the ZIP? I usually use [7-zip](https://7-zip.org/)

**Comment by Sithuk** [comment]
I used 7-zip. I’ll be interested to read if you can duplicate the issue. Thank you for the continued support.

**Comment by Sithuk** [comment]
I tried Stars using wine in a KDE Neon and the serial wasn’t saved either. Could be wine?

**Comment by raptor** [comment]
it's not WINE as I've been using it for years with no issue. Might it be the serial? You could try one of the publicly known ones and see if you get better luck.

**Comment by raptor** [comment]
I updated the otvdm engine and released a new version to test:

https://github.com/stars-4x/starswine/releases/download/5.0-beta/starswine5.zip

Can you please see if that works?

**Comment by Sithuk** [comment]
Good news. I've figured out what the issue was. I was using one of the publically listed serial codes at the following page. 

http://starsfaq.com/download.htm

There are two groups of codes. 
1. There is a group of four serial codes at the top of the list.
2. Then there is a further list of 38 serial codes in a second group. The second group are listed as "from google".

All the codes are accepted by Stars! and appear to work, but only the first group are "remembered". Codes from the second group trigger a prompt to re-enter them.

Starsautohost has the following note about Stars! version 2.6j/2.7j.
"Version J also included a blacklist of serial codes that had been leaked to the internet."
https://wiki.starsautohost.org/wiki/Patches_and_versions

So the issue was the blacklist introduced in version 2.6j/2.7j.

It might be helpful to place a warning on the front page about the serial code blacklist? So players should either use one of the serial codes from the first group of four or that new codes can be bought from StarsAutohost for a small donation (https://starsautohost.org/sahforum2/index.php?t=msg&th=1158&start=0&rid=78&S=1c6cad4a541f5b350ac270f0e94c7243).

Thank you for creating an updated winestars with the latest otvdm engine and for the support to try to resolve the issue. I've tested the latest starswine5 and it works.

**Comment by raptor** [comment]
Thanks for solving the mystery! I will make a note of this. Someone else also partially reversed the serial algorithm and dumped a bunch more likely serials here (I have not tested these):

https://github.com/ricks03/TotalHost/blob/master/serialC.txt

**Comment by ricks03** [comment]
> Thanks for solving the mystery! I will make a note of this. Someone else also partially reversed the serial algorithm and dumped a bunch more likely serials here (I have not tested these):
> 
> https://github.com/ricks03/TotalHost/blob/master/serialC.txt

Not partially :-)   I just only put up those that started with C. Seemed like plenty for any possible usage.
